#Servidor de archivos Azure
azure:
  storage:
    container:
      name: 
        comprobante-pago
    connection:
       string: DefaultEndpointsProtocol=https;AccountName=testaname;AccountKey=ynnrnSuLoHcROgcLmsmhuLOaOBDLLCLLw4yCPbHaSWVjA5b2jL8vUGC80VMSiSRx/WJWKXiCT7Or+AStH7AqOQ==;EndpointSuffix=core.windows.net